/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/punktsok": {
    /** Søk etter adresser innen en viss radius. Sortert etter distanse fra punkt. Respons inkluderer distansen fra punktet i meter. Geografiske koordinater må benyttes. */
    get: {
      parameters: {
        query: {
          /** Koordinatsystem for punktet du søker etter. Oppgis som srid, f.eks. 25833 eller 3857. Standardinnstilling er 4258 */
          koordsys?: number;
          /** Antall treff per side. */
          treffPerSide?: number;
          /** Sidenummeret som vises. Første side = 0 */
          side?: number;
          /** Garanterer at dataene som returneres er ascii-kompatible. */
          asciiKompatibel?: boolean;
          /** Geografiske lon/øst koordinater, med mindre annet er spesifisert. */
          lon: number;
          /** Koordinatsystem som adressegeometrien skal returneres i. Oppgis som srid, f.eks. 25833 eller 3857. Standardinnstilling er 4258 */
          utkoordsys?: number;
          /** Radius for søket i hele meter */
          radius: number;
          /** Geografiske lat/nord koordinater, med mindre annet er spesifisert. */
          lat: number;
          /** Kommaseparert liste med objekter du ikke ønsker å filtrere ut. For å hente ut underobjekter bruk "."-notasjon, f.eks.: &filtrer=adresser.kommunenummer,adresser.representasjonspunkt */
          filtrer?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["OutputGeoPointList"];
        };
      };
    };
  };
  "/sok": {
    /** Søk etter adresser. Minst ett søkeparameter må benyttes. For generelle søk så anbefales det å benytte søkeparameteret "sok", og så eventuelt snevre inn resultatet ved å bruke de andre parameterene. For eksempel sok?sok=munkegata&kommunenummer=5001 */
    get: {
      parameters: {
        query: {
          /** Del av adressenummer (husnummer) som er et nummer og eventuelt en bokstav, f.eks 23B */
          nummer?: number;
          /** Sidenummeret som vises. Første side = 0 */
          side?: number;
          /** Del av en matrikkeladresse der vegadresse ikke er innført, - eller vegadressens knytning til matrikkelenhet (grunneiendom eller feste, - gir her ikke knyting mot seksjon) */
          gardsnummer?: number;
          /** Navn på gate, veg, sti, plass eller område som er ført i matrikkelen (eksempel Sørumvegen). */
          adressenavn?: string;
          /** Navn på poststed i henhold til Postens egne lister */
          poststed?: string;
          /** Vegadresse er offisiell adresse i form av et adressenavn og et adressenummer (Storgata 10). Der kommunen ikke har gått over til vegadresser, vil det finnes matrikkeladresse på formen: gårdsnummer/ bruksnummer/ev festenummer-ev undernummer (10/2) Begge adressetypene kan ha bruksenhetsnummer (leiligheter) og adressetilleggsnavn. Begge adressetypene vises som standard, hvis man kun ønsker å se en av de kan man spesifisere adressetypen via dette parameteret. */
          objtype?: "Vegadresse" | "Matrikkeladresse";
          /** Offisiell adresse som tekststreng (eksempel «Ven, Sørumvegen 45»), men uten eventuelt bruksenhetsnummer for leiligheter */
          adressetekst?: string;
          /** Fortløpende nummerering av matrikkeladresser med samme gårds-, bruks- og festenummer. */
          undernummer?: number;
          /** Kommaseparert liste med objekter du ikke ønsker å filtrere ut. For å hente ut underobjekter bruk "."-notasjon, f.eks.: &filtrer=adresser.kommunenummer,adresser.representasjonspunkt */
          filtrer?: string;
          /** Generelt adressesøk over nesten alle feltene. Wildcard-søk med "*" er støttet. Flere detaljer vil gi mer nøyaktige søk. Bare legg til ekstra opplysninger adskilt med mellomrom. F.eks.: ?sok=munkegata 1 trondheim */
          sok?: string;
          /** Del av offisiell adresse (bruksenhetsnummer) til f.eks en leilighet i flerboligbygg. Bokstaven og de to første tallene angir etasje, de to siste angir leilighetens nummer i etasjen, regnet fra venstre mot høyre. Eksempel: "H0102", "K0101" */
          bruksenhetsnummer?: string;
          /** Del av en matrikkeladresse der vegadresse ikke er innført, - eller vegadressens knytning til matrikkelenhet (grunneiendom eller feste, - gir her ikke knytning mot seksjon) */
          festenummer?: number;
          /** Unik identifikasjon av et postnummerområde. Tekstverdi som må bestå av 4 tall. 0340 er for eksempel gyldig, mens 340 er ikke gyldig. */
          postnummer?: string;
          /** Antall treff per side. */
          treffPerSide?: number;
          /** Garanterer at dataene som returneres er ascii-kompatible. */
          asciiKompatibel?: boolean;
          /** Del av en matrikkeladresse der vegadresse ikke er innført, - eller vegadressens knytning til matrikkelenhet (grunneiendom eller feste, - gir her ikke knyting mot seksjon) */
          bruksnummer?: number;
          /** Nummerering av kommunen i henhold til Statistisk sentralbyrå sin offisielle liste. Tekstverdi som må bestå av 4 tall. 0301 er for eksempel gyldig, mens 301 er ikke gyldig. */
          kommunenummer?: string;
          /** Navn (norsk) på en kommune */
          kommunenavn?: string;
          /** Koordinatsystem som adressegeometrien skal returneres i. Oppgis som srid, f.eks. 25833 eller 3857. Standardinnstilling er 4258 */
          utkoordsys?: number;
          /** Nedarvet bruksnavn, navn på en institusjon eller bygning eller grend brukt som del av den offisielle adressen */
          adressetilleggsnavn?: string;
          /** Modifiserer "sok"-feltet, standardverdi er "AND". Velg om søket skal kreve at hver eneste søkeparameter finnes i treffet, eller om det holder med treff på kun ett parameter. F.eks. vil "?sok=munkegata 1 trondheim&sokemodus=OR" returnere alt som inneholder "munkegata" OG/ELLER tallet "1" OG/ELLER "trondheim". */
          sokemodus?: "AND" | "OR";
          /** Nummer som entydig identifiserer adresserbare gater, veger, stier, plasser og områder som er ført i matrikkelen innen kommunen */
          adressekode?: number;
          /** Del av adressenummer (husnummer) som er et nummer og en eventuelt en bokstav, f.eks 23B. For å kun søke på adresser uten noen bokstav så inkluderer man "bokstav=" i søkestrengen uten å fylle inn noen verdi. */
          bokstav?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["OutputAdresseList"];
        };
      };
    };
  };
}

export interface definitions {
  GeomPoint: {
    /** @description Koordinatsystem til punktet. Angitt vha EPSG-kode. */
    epsg?: string;
    /**
     * Format: float
     * @description Geografiske lat/nord koordinater, med mindre annet er spesifisert.
     */
    lat: number;
    /**
     * Format: float
     * @description Geografiske lon/øst koordinater, med mindre annet er spesifisert.
     */
    lon: number;
  };
  HitMetadata: {
    /**
     * @description Garanterer at dataene som returneres er ascii-kompatible.
     * @default true
     */
    asciiKompatibel?: boolean;
    /**
     * Format: int32
     * @description Sidenummeret som vises. Første side = 0
     */
    side?: number;
    /** @description Søkestrengen som ble sendt inn til API-et. */
    sokeStreng?: string;
    /**
     * Format: int32
     * @description Antall treff som søket returnerte.
     */
    totaltAntallTreff?: number;
    /**
     * Format: int32
     * @description Antall treff per side.
     * @default 10
     */
    treffPerSide?: number;
    /**
     * Format: int32
     * @description Hvilket resultatnummer det første objektet du ser har.
     */
    viserFra?: number;
    /**
     * Format: int32
     * @description Hvilket resultatnummer det siste objektet du ser har.
     */
    viserTil?: number;
  };
  OutputAdresse: {
    /**
     * Format: int32
     * @description Nummer som entydig identifiserer adresserbare gater, veger, stier, plasser og områder som er ført i matrikkelen innen kommunen
     */
    adressekode?: number;
    /** @description Navn på gate, veg, sti, plass eller område som er ført i matrikkelen (eksempel Sørumvegen). */
    adressenavn?: string;
    /** @description Del av offisiell adresse, men uten bruksenhetsnummer som ligger til bruksenheter/boliger (ligger her som egenskap til vegadressen) Eksempel: "Storgata 2B" eller "123/4-2" Der det i tillegg er adressetilleggsnavn: "Haugen, Storgata 2B" eller "Midtgard, 123/4-2" */
    adressetekst?: string;
    /** @description Del av offisiell adresse, men uten bruksenhetsnummer som ligger til bruksenheter/boliger og adressetilleggsnavn Eksempel: "Storgata 2B" eller "123/4-2" */
    adressetekstutenadressetilleggsnavn?: string;
    /** @description Nedarvet bruksnavn, navn på en institusjon eller bygning eller grend brukt som del av den offisielle adressen */
    adressetilleggsnavn?: string;
    /** @description Del av adressenummer (husnummer) som er et nummer og en eventuelt en bokstav, f.eks 23B. For å kun søke på adresser uten noen bokstav så inkluderer man "bokstav=" i søkestrengen uten å fylle inn noen verdi. */
    bokstav?: string;
    bruksenhetsnummer?: string[];
    /**
     * Format: int32
     * @description Del av en matrikkeladresse der vegadresse ikke er innført, - eller vegadressens knytning til matrikkelenhet (grunneiendom eller feste, - gir her ikke knyting mot seksjon)
     */
    bruksnummer?: number;
    /**
     * Format: int32
     * @description Del av en matrikkeladresse der vegadresse ikke er innført, - eller vegadressens knytning til matrikkelenhet (grunneiendom eller feste, - gir her ikke knytning mot seksjon)
     */
    festenummer?: number;
    /**
     * Format: int32
     * @description Del av en matrikkeladresse der vegadresse ikke er innført, - eller vegadressens knytning til matrikkelenhet (grunneiendom eller feste, - gir her ikke knyting mot seksjon)
     */
    gardsnummer?: number;
    /** @description Navn (norsk) på en kommune */
    kommunenavn?: string;
    /** @description Nummerering av kommunen i henhold til Statistisk sentralbyrå sin offisielle liste. Tekstverdi som må bestå av 4 tall. 0301 er for eksempel gyldig, mens 301 er ikke gyldig. */
    kommunenummer?: string;
    /**
     * Format: int32
     * @description Del av adressenummer (husnummer) som er et nummer og eventuelt en bokstav, f.eks 23B
     */
    nummer?: number;
    /**
     * @description Vegadresse er offisiell adresse i form av et adressenavn og et adressenummer (Storgata 10). Der kommunen ikke har gått over til vegadresser, vil det finnes matrikkeladresse på formen: gårdsnummer/ bruksnummer/ev festenummer-ev undernummer (10/2) Begge adressetypene kan ha bruksenhetsnummer (leiligheter) og adressetilleggsnavn. Begge adressetypene vises som standard, hvis man kun ønsker å se en av de kan man spesifisere adressetypen via dette parameteret.
     * @enum {string}
     */
    objtype?: "Vegadresse" | "Matrikkeladresse";
    /**
     * Format: date-time
     * @description Dato for siste endring på objektdataene
     */
    oppdateringsdato?: string;
    /** @description Unik identifikasjon av et postnummerområde. Tekstverdi som må bestå av 4 tall. 0340 er for eksempel gyldig, mens 340 er ikke gyldig. */
    postnummer?: string;
    /** @description Navn på poststed i henhold til Postens egne lister */
    poststed?: string;
    representasjonspunkt?: definitions["GeomPoint"];
    /** @description Angivelse om stedfestingen (koordinatene) er kontrollert og funnet i orden (verifisert) */
    stedfestingverifisert?: boolean;
    /**
     * Format: int32
     * @description Fortløpende nummerering av matrikkeladresser med samme gårds-, bruks- og festenummer.
     */
    undernummer?: number;
  };
  OutputAdresseList: {
    adresser?: definitions["OutputAdresse"][];
    metadata?: definitions["HitMetadata"];
  };
  OutputGeoPoint: {
    /**
     * Format: int32
     * @description Nummer som entydig identifiserer adresserbare gater, veger, stier, plasser og områder som er ført i matrikkelen innen kommunen
     */
    adressekode?: number;
    /** @description Navn på gate, veg, sti, plass eller område som er ført i matrikkelen (eksempel Sørumvegen). */
    adressenavn?: string;
    /** @description Del av offisiell adresse, men uten bruksenhetsnummer som ligger til bruksenheter/boliger (ligger her som egenskap til vegadressen) Eksempel: "Storgata 2B" eller "123/4-2" Der det i tillegg er adressetilleggsnavn: "Haugen, Storgata 2B" eller "Midtgard, 123/4-2" */
    adressetekst?: string;
    /** @description Del av offisiell adresse, men uten bruksenhetsnummer som ligger til bruksenheter/boliger og adressetilleggsnavn Eksempel: "Storgata 2B" eller "123/4-2" */
    adressetekstutenadressetilleggsnavn?: string;
    /** @description Nedarvet bruksnavn, navn på en institusjon eller bygning eller grend brukt som del av den offisielle adressen */
    adressetilleggsnavn?: string;
    /** @description Del av adressenummer (husnummer) som er et nummer og en eventuelt en bokstav, f.eks 23B. For å kun søke på adresser uten noen bokstav så inkluderer man "bokstav=" i søkestrengen uten å fylle inn noen verdi. */
    bokstav?: string;
    bruksenhetsnummer?: string[];
    /**
     * Format: int32
     * @description Del av en matrikkeladresse der vegadresse ikke er innført, - eller vegadressens knytning til matrikkelenhet (grunneiendom eller feste, - gir her ikke knyting mot seksjon)
     */
    bruksnummer?: number;
    /**
     * Format: int32
     * @description Del av en matrikkeladresse der vegadresse ikke er innført, - eller vegadressens knytning til matrikkelenhet (grunneiendom eller feste, - gir her ikke knytning mot seksjon)
     */
    festenummer?: number;
    /**
     * Format: int32
     * @description Del av en matrikkeladresse der vegadresse ikke er innført, - eller vegadressens knytning til matrikkelenhet (grunneiendom eller feste, - gir her ikke knyting mot seksjon)
     */
    gardsnummer?: number;
    /** @description Navn (norsk) på en kommune */
    kommunenavn?: string;
    /** @description Nummerering av kommunen i henhold til Statistisk sentralbyrå sin offisielle liste. Tekstverdi som må bestå av 4 tall. 0301 er for eksempel gyldig, mens 301 er ikke gyldig. */
    kommunenummer?: string;
    /** Format: float */
    meterDistanseTilPunkt?: number;
    /**
     * Format: int32
     * @description Del av adressenummer (husnummer) som er et nummer og eventuelt en bokstav, f.eks 23B
     */
    nummer?: number;
    /**
     * @description Vegadresse er offisiell adresse i form av et adressenavn og et adressenummer (Storgata 10). Der kommunen ikke har gått over til vegadresser, vil det finnes matrikkeladresse på formen: gårdsnummer/ bruksnummer/ev festenummer-ev undernummer (10/2) Begge adressetypene kan ha bruksenhetsnummer (leiligheter) og adressetilleggsnavn. Begge adressetypene vises som standard, hvis man kun ønsker å se en av de kan man spesifisere adressetypen via dette parameteret.
     * @enum {string}
     */
    objtype?: "Vegadresse" | "Matrikkeladresse";
    /**
     * Format: date-time
     * @description Dato for siste endring på objektdataene
     */
    oppdateringsdato?: string;
    /** @description Unik identifikasjon av et postnummerområde. Tekstverdi som må bestå av 4 tall. 0340 er for eksempel gyldig, mens 340 er ikke gyldig. */
    postnummer?: string;
    /** @description Navn på poststed i henhold til Postens egne lister */
    poststed?: string;
    representasjonspunkt?: definitions["GeomPoint"];
    /** @description Angivelse om stedfestingen (koordinatene) er kontrollert og funnet i orden (verifisert) */
    stedfestingverifisert?: boolean;
    /**
     * Format: int32
     * @description Fortløpende nummerering av matrikkeladresser med samme gårds-, bruks- og festenummer.
     */
    undernummer?: number;
  };
  OutputGeoPointList: {
    adresser?: definitions["OutputGeoPoint"][];
    metadata?: definitions["HitMetadata"];
  };
}

export interface operations {}

export interface external {}
