name: Rebuild cache on a CRON Schedule

on:
  schedule:
    - cron: "5 0/4 * * *"
jobs:
  build:
    name: Rebuild cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Rebuild script
        run: deno test --allow-all ./scripts/rebuild-cache.ts
